"""added user avatar attribute to User

Revision ID: 8f48e33c88e7
Revises: 15930fd9b2a3
Create Date: 2024-03-14 18:08:54.726422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f48e33c88e7'
down_revision = '15930fd9b2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_avatar', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_avatar')

    # ### end Alembic commands ###
