"""added palette, color, and color accociation models

Revision ID: dee2e1639bcc
Revises: 8f48e33c88e7
Create Date: 2024-03-15 10:03:15.067230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee2e1639bcc'
down_revision = '8f48e33c88e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('usage_frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_palettes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palette_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('combined_scores', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_color_associations_color_id_colors')),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], name=op.f('fk_color_associations_palette_id_palettes')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_associations')
    op.drop_table('palettes')
    op.drop_table('colors')
    # ### end Alembic commands ###
